baseURL = 'https://blog.yaxley.in/'
languageCode = 'en-in'
title = 'An archive of my own'
theme = 'cactus'
copyright = "Yaxley Peaks"


#aaammm
# fix 1

[params]
description = "*Hello o/*, You successfully made it here! :D"
themeColor = "theme-base-08"
colorTheme = "light"
mainSection = "posts"
showAllPostsOnHomePage = true
tocInline = true
logo = "images/favicon.ico"
showProjectsList = true
projectsUrl = "https://github.com/yaxley-peaks"

[params.comments]
enabled = false

[params.buttons]
enabled = true

[params.webrings]
enabled = true

[params.friends]
enabled = true

[markup]
defaultMarkdownHandler = 'org'


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "About"
url = "/about"
weight = 3
